services:
  dispatcher:
    build:
      context: .
      dockerfile: cmd/dispatcher/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - WORKERS=worker-1:8080,worker-2:8080,worker-3:8080
      - PORT=8080
    depends_on:
      - worker-1
      - worker-2
      - worker-3
    networks: [backend]

  worker-1:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    networks: [backend]

  worker-2:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    networks: [backend]

  worker-3:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    networks: [backend]

networks:
  backend:
